config/routes.rb
MeurioAccounts::Application.routes.draw do
  root 'casino/sessions#new'

  get '/sessions', to: redirect('/edit_profile')

  mount CASino::Engine => '/'
  get '/logout', to: 'casino/sessions#logout', as: :logout
  get '/login', to: 'casino/sessions#login', as: :login

  devise_for :users, :controllers => {:registrations => "registrations", :passwords => "passwords"}

  resources :users, only: [:edit, :create, :update, :show] do
    resources :memberships, only: [:create]
    resources :segment_subscriptions, only: [:create]
  end

  get 'edit_profile' => 'users#edit', as: :edit_profile
  get 'sign_in_after_sign_up' => 'users#sign_in', as: :sign_in_after_sign_up

  match 'validate_email' => "users#validate_email", as: :validate_email, via: [:get, :post]

  namespace :api do
    namespace :v1, constraints: { format: 'json' } do
      resources :users, only: [:create]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  validates :email, :first_name, :last_name, :organization_id, presence: true
  validates :email, format: { with: /([0-9a-zA-Z]+[-._+&amp;])*[0-9a-zA-Z\_\-]+@([-0-9a-zA-Z]+[.])+[a-zA-Z]{2,6}/ }
  validates :password, on: :create, length: { minimum: 6, maximum: 128 }
  validates :secondary_email, format: { with: /([0-9a-zA-Z]+[-._+&amp;])*[0-9a-zA-Z\_\-]+@([-0-9a-zA-Z]+[.])+[a-zA-Z]{2,6}/ }, allow_blank: true
  validates :phone, format: { with: /\([\d]{2}\)\s[\d]{8,9}/ }, allow_blank: true
  validates :website, format: { with: /(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?/ }, allow_blank: true
  validates :auth_token, uniqueness: true

  has_many :memberships, inverse_of: :user
  has_many :organizations, through: :memberships
  belongs_to :organization

  accepts_nested_attributes_for :memberships

  mount_uploader :avatar, AvatarUploader

  bitmask :availability, as: AVAILABILITY_OPTIONS
  bitmask :topics, as: TOPIC_OPTIONS

  before_validation :set_auth_token
  before_validation :process_website
  after_create :create_first_membership
  after_create { self.delay.import_image_from_gravatar }
  after_save { self.delay.update_location_and_mailchimp }

  def update_location_and_mailchimp
    self.update_location
    self.update_mailchimp_subscription
  end

  def update_location
    self.fetch_address if self.postal_code.present?
    self.locate_ip if self.ip.present? and self.postal_code.blank?
  end

  def update_mailchimp_subscription
    begin
      subscription = Gibbon::API.lists.subscribe(
        id: ENV["MAILCHIMP_LIST_ID"],
        email: { email: self.email },
        merge_vars: {
          FNAME: self.first_name,
          LNAME: self.last_name,
          ORG: self.organization.name,
          CITY: self.city,
          PHONE: self.phone,
          LOGINLINK: self.login_url,
          DISTRICT: self.address_district,
          groupings: [
            { id: 1, groups: self.translated_skills },
            { id: 49, groups: self.organizations.map{|o| o.name} },
            { id: 73, groups: self.translated_topics }
          ]
        },
        double_optin: false,
        update_existing: true,
        replace_interests: true
      )

      self.update_column :mailchimp_euid, subscription["euid"]
    rescue Exception => e
      Appsignal.add_exception e
      Rails.logger.error e
    end
  end

  def name
    "#{first_name} #{last_name}"
  end

  def fetch_address
    begin
      json = JSON.parse(open("http://brazilapi.herokuapp.com/api?cep=#{self.postal_code}").read)
      if(json[0]["cep"]["valid"])
        address = json[0]["cep"]["data"]
        if(self.city != address["cidade"] || self.address_street != "#{address["tp_logradouro"]} #{address["logradouro"]}" || self.address_district != address["bairro"] || self.state != address["uf"])
          self.update_columns(city: address["cidade"], address_street: "#{address["tp_logradouro"]} #{address["logradouro"]}", address_district: address["bairro"], state: address["uf"])
        end
      end
    rescue Exception => e
      Appsignal.add_exception e
      Rails.logger.error e
    end
  end

  def locate_ip
    begin
      location = Ipaddresslabs.locate(self.ip)
      self.update_columns(
        city: location["geolocation_data"]["city"],
        state: location["geolocation_data"]["region_name"],
        country: location["geolocation_data"]["country_name"]
      )
    rescue Exception => e
      Appsignal.add_exception e
      Rails.logger.error e
    end
  end

  def translated_skills
    self.skills.present? ? self.skills.map { |s| I18n.t("skills.#{s}") } : []
  end

  def translated_topics
    self.topics.present? ? self.topics.map { |t| I18n.t("topics.#{t}") } : []
  end

  def import_image_from_gravatar
    if (self.avatar_url == self.avatar.default_url) and self.gravatar_exists?
      self.update_attribute(:remote_avatar_url, self.gravatar_url)
    end
  end

  def gravatar_url
    "http://gravatar.com/avatar/#{Digest::MD5.hexdigest(self.email.downcase)}.png"
  end

  def gravatar_exists?
    url = "#{self.gravatar_url}?d=404"
    response = Net::HTTP.get_response(URI.parse(url))
    response.code.to_i != 404
  end

  def login_url
    "http://#{ENV['HOST']}?user_token=#{self.auth_token}&user_email=#{self.email}"
  end

  private

  def set_auth_token
    return if self.auth_token.present?

    begin
      self.auth_token = SecureRandom.hex
    end while self.class.exists?(auth_token: self.auth_token)
  end

  def process_website
    self.website = "http://#{self.website}" if self.website.present? && self.website.index("http://").nil?
  end

  def create_first_membership
    Membership.create organization: self.organization, user: self
  end
end

app/controllers/api/v1/users_controller.rb
class API::V1::UsersController < APIController
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.json { render :show, status: :created, location: @user }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :organization_id)
  end
end

app/controllers/users_controller.rb
# The UserController#create is not been used! It's the DeviseRegistration instead

class UsersController < InheritedResources::Base
  load_and_authorize_resource
  skip_authorize_resource :only => [:create, :update, :validate_email, :create_password, :sign_in]
  skip_before_action :verify_authenticity_token, only: [:create, :update]
  before_action :set_allowed_user, only: [:edit, :update]

  respond_to :json

  def update
    @user.availability = params[:user][:availability] if params[:user][:availability].present?
    @user.skills = params[:user][:skills] if params[:user][:skills].present?
    @user.topics = params[:user][:topics] if params[:user][:topics].present?
    @user.ip = request.remote_ip

    update! do |success, failure|
      # TODO: find out why we are using redirect_url here, if it's useless, take it off
      success.html { redirect_to session[:redirect_url].present? ? session[:redirect_url] : "#{ENV['MR_PATH']}/users/#{@user.id}" }
      failure.html { render :edit }
    end
  end

  def sign_in
    sign_in_with_casino params[:user][:email], params[:user][:password]
  end

  def validate_email
    if request.post?
      if user = User.find_by_email(params[:email])
        user.send_reset_password_instructions
        redirect_to root_path(flash: 'Enviamos um email para você criar sua senha')
      else
        redirect_to new_user_registration_path(email: params[:email], first_name: params[:first_name], last_name: params[:last_name])
      end
    end
  end

  # TODO: We need an API, for God sake!
  def set_allowed_user
    unless request.format.json?
      @user = current_account if @user.nil? || !current_account.admin?
    end
  end

  def permitted_params
    { user: params.require(:user).permit(
      :avatar, :first_name, :last_name, :email, :bio, :birthday, :profession, :postal_code, :phone, :secondary_email,
      :gender, :public, :facebook, :twitter, :website, :availability, :skills, :topics, :ip, :application_slug,
      :password, :organization_id, memberships_attributes: [:organization_id], organization_ids: [])
    }
  end
end

app/views/users/_availability.html.slim
.large-6.columns
  .availability
    h3= t slice_type(availability_options.first)
    - availability_options.each_slice(3) do |values|
      .day
        span= t slice_day(values.first)
        - values.each do |value|
          input *{type: 'checkbox', name: 'user[availability][]', value: value, checked: @user.availability?(value), id: "user_availability_#{value}"}
          = label_tag "user_availability_#{value}", t(slice_shift(value))

app/views/users/edit.html.slim
.row
  .large-10.columns.large-centered
    .row
      = form_for @user, data: {abide: true} do |f|
        .large-3.columns
          = image_tag @user.avatar.square.url, class: :avatar
          = f.file_field :avatar
          = f.hidden_field :avatar_cache
          a.btn Alterar Imagem
        .large-9.columns
          .wrapper
            .row.header
              .large-12.columns
                h2 Perfil
                | Nossos membros querem te conhecer. Conte pra todos um pouco mais sobre você!
            .row
              .large-12.columns
                = f.label :organization_id
                = f.collection_select :organization_id, Organization.all.order(:city), :id, :city, required: true
            .row
              .large-6.columns
                = f.label :first_name
                = f.text_field :first_name, required: true
              .large-6.columns
                = f.label :last_name
                = f.text_field :last_name, required: true

            .row
              .large-6.columns
                = f.label :profession
                = f.text_field :profession
              .large-6.columns
                = f.label :website
                = f.url_field :website, placeholder: "nossascidades.org"
                small.error O website deve ser válido
            .row
              .large-12.columns
                = f.label :bio
                = f.text_area :bio

            .row
              .large-6.columns
                = f.label :facebook
                  | facebook.com/
                  = f.text_field :facebook
              .large-6.columns
                = f.label :twitter
                  | twitter.com/
                  = f.text_field :twitter

            .row
              .large-12.columns
                = f.check_box :public
                = f.label :public

            .row#memberships
              .large-12.columns
                h3 De quais Redes de Mobilização você gostaria de receber emails?
              .large-12.columns
                = collection_check_boxes(:user, :organization_ids, Organization.all.order(:created_at), :id, :name) do |b|
                  .organization_check
                    = b.check_box
                    = b.label(style: "background: url(#{b.object.avatar_url}) center center no-repeat;background-size: cover")

            hr
            .row.header
              .large-12.columns
                h2 Informações privadas
                | Somente você e a equipe da Rede Nossas Cidades poderão ver essas informações.
            .row
              .large-6.columns
                = f.label :email
                = f.email_field :email, required: true
                small.error O email é obrigatório e deve ser válido
              .large-6.columns
                = f.label :secondary_email
                = f.email_field :secondary_email
                small.error O email secundário deve ser válido

            .row
              .large-6.columns
                = f.label :birthday
                = f.text_field :birthday, class: [:date], value: @user.birthday.present? ? @user.birthday.strftime("%d/%m/%Y") : nil
              .large-6.columns
                = f.radio_button :gender, 'male'
                = f.label :gender, 'Masculino', value: 'male'
                = f.radio_button :gender, 'female'
                = f.label :gender, 'Feminino', value: 'female'
                = f.radio_button :gender, 'other'
                = f.label :gender, 'Outro', value: 'other'

            .row
              .large-6.columns
                = f.label :postal_code
                = f.text_field :postal_code, class: [:postal_code]
              .large-6.columns
                = f.label :phone
                = f.text_field :phone, class: [:phone]

            hr
            .row.header
              .large-12.columns
                h2 Voluntarie-se pela sua cidade
                | Essas informações serão usadas para conectar você com as oportunidades de voluntariado da Rede.

            .row.topics
              .large-12.columns
                h3 Que temas são do seu interesse?
              - User.values_for_topics.sort.each do |value|
                .large-12.columns
                  input *{type: 'checkbox', name: 'user[topics][]', value: value, checked: @user.topics?(value), id: value}
                  = label_tag value, t("topics.#{value}")

            .row.skills
              .large-12.columns
                h3 Quais são os seus talentos?
              - SKILL_OPTIONS.sort.each do |value|
                .large-12.columns
                  input *{type: 'checkbox', name: 'user[skills][]', value: value, checked: @user.skills && @user.skills.include?(value), id: "user_skills_#{value}"}
                  = label_tag value, t("skills.#{value}")

            .row
              - [ values_for_local_availability, values_for_remote_availability ].each do |values|
                = render 'availability', availability_options: values

            .row
              .large-12.columns
                | #{f.submit 'Salvar Perfil'} ou #{link_to "Sair", logout_path(service: login_path), class: [:alert]}

app/views/users/show.html.slim
.row
  .large-12.columns
    h2= "#{@user.first_name} #{@user.last_name}"
    hr
    h2= @user.email
    h2= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'logout'

app/views/users/validate_email.html.slim
.row
  .registration.large-5.medium-8.medium-centered.columns
    = form_tag validate_email_path, method: :post, class: :validate_email
      h2 Crie seu perfil com suas preferências e interesses para receber as oportunidades de ação!
      .signup Já é membro? #{link_to 'Faça seu login', new_session_path(:user)}
      .row
        .first_name.large-6.columns
          = text_field_tag :first_name, nil, placeholder: 'Nome'
        .last_name.large-6.columns
          = text_field_tag :last_name, nil, placeholder: 'Sobrenome'
      .row
        .large-12.columns
      		= email_field_tag :email, nil, placeholder: 'Email', required: true
      .row
        .large-12.columns
          = submit_tag 'Avançar'